import { useMemo } from 'react'
import { useReadContracts } from 'wagmi'
import type { Pool } from '../services/betService'
import type { Grid } from '../types/grid'
import { getAbsoluteCellId, getWindowIdAtTime, getSlotKey } from '../lib/gridSlots'

// PariHook public mapping getters (auto-generated by Solidity for public mappings)
const PARI_HOOK_STAKES_ABI = [
    {
        name: 'cellStakes',
        type: 'function',
        stateMutability: 'view',
        inputs: [
            { name: 'windowId', type: 'uint256' },
            { name: 'cellId', type: 'uint256' },
        ],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        name: 'windowTotals',
        type: 'function',
        stateMutability: 'view',
        inputs: [{ name: 'windowId', type: 'uint256' }],
        outputs: [{ name: '', type: 'uint256' }],
    },
] as const

// Must match GridConfig.frozenWindows in PariHook (CLAUDE.md spec)
const FROZEN_WINDOWS = 3
// Number of bettable windows (CLAUDE.md: +4, +5, +6 relative to NOW)
const BETTABLE_COUNT = 3
// Max cells to scan per window (limits multicall size)
const MAX_CELLS_PER_WINDOW = 60

/**
 * Reads on-chain cellStakes and windowTotals from PariHook via wagmi multicall.
 * Returns a map keyed by "${windowId}_${cellId}" with the parimutuel multiplier:
 *   multiplier = (windowTotal × 0.98) / cellStake
 *
 * Falls back to empty object when:
 * - No pool is known yet
 * - Contract doesn't expose these mappings (graceful no-op)
 * - No visible price range provided
 */
export function usePoolMultipliers(
    pool: Pool | null,
    grid: Grid | null,
    visibleMinPrice: number,
    visibleMaxPrice: number,
): { multipliers: Record<string, number>; windowTotals: Record<number, number>; cellStakes: Record<string, number> } {
    const contractAddress = pool?.poolKey.hooks as `0x${string}` | undefined

    // Derive bettable windowIds and visible cellId range
    const { bettableWindowIds, cellIds } = useMemo(() => {
        if (!pool || !grid || !isFinite(visibleMinPrice) || !isFinite(visibleMaxPrice)) {
            return { bettableWindowIds: [] as number[], cellIds: [] as number[] }
        }

        const currentWindowId = getWindowIdAtTime(Date.now(), pool, grid)

        const bettableWindowIds: number[] = []
        for (let i = 1; i <= BETTABLE_COUNT; i++) {
            bettableWindowIds.push(currentWindowId + FROZEN_WINDOWS + i)
        }

        // Absolute cell IDs for the visible price range
        const startCellId = getAbsoluteCellId(visibleMinPrice, grid.price_interval || 2)
        const endCellId = getAbsoluteCellId(visibleMaxPrice, grid.price_interval || 2) + 1
        const cellIds: number[] = []
        for (let c = startCellId; c <= Math.min(endCellId, startCellId + MAX_CELLS_PER_WINDOW - 1); c++) {
            cellIds.push(c)
        }

        return { bettableWindowIds, cellIds }
    }, [pool, grid, visibleMinPrice, visibleMaxPrice])

    // Build multicall array: [windowTotals × 3] then [cellStakes × nCells × 3]
    const contracts = useMemo(() => {
        if (!contractAddress || bettableWindowIds.length === 0 || cellIds.length === 0) return []

        const calls: {
            address: `0x${string}`
            abi: typeof PARI_HOOK_STAKES_ABI
            functionName: 'windowTotals' | 'cellStakes'
            args: readonly [bigint] | readonly [bigint, bigint]
        }[] = []

        for (const wid of bettableWindowIds) {
            calls.push({
                address: contractAddress,
                abi: PARI_HOOK_STAKES_ABI,
                functionName: 'windowTotals',
                args: [BigInt(wid)] as const,
            })
        }

        for (const wid of bettableWindowIds) {
            for (const cid of cellIds) {
                calls.push({
                    address: contractAddress,
                    abi: PARI_HOOK_STAKES_ABI,
                    functionName: 'cellStakes',
                    args: [BigInt(wid), BigInt(cid)] as const,
                })
            }
        }

        return calls
    }, [contractAddress, bettableWindowIds, cellIds])

    type ContractResult = { status: 'success' | 'failure'; result?: unknown }
    const { data: rawData } = useReadContracts({
        contracts,
        query: {
            enabled: contracts.length > 0,
            refetchInterval: 10_000,
        },
    })
    const data = rawData as ReadonlyArray<ContractResult> | undefined

    return useMemo(() => {
        if (!data || bettableWindowIds.length === 0 || cellIds.length === 0) {
            return { multipliers: {}, windowTotals: {}, cellStakes: {} }
        }

        const nWindows = bettableWindowIds.length
        const nCells = cellIds.length

        // Parse windowTotals (first nWindows results)
        const rawWindowTotals: Record<number, bigint> = {}
        for (let i = 0; i < nWindows; i++) {
            const r = data[i]
            if (r?.status === 'success' && r.result != null) {
                rawWindowTotals[bettableWindowIds[i]] = r.result as bigint
            }
        }

        // Parse cellStakes and compute multipliers
        const multipliers: Record<string, number> = {}
        const cellStakes: Record<string, number> = {}
        for (let wi = 0; wi < nWindows; wi++) {
            const windowId = bettableWindowIds[wi]
            const windowTotal = rawWindowTotals[windowId] ?? 0n
            if (windowTotal === 0n) continue

            // netPool = windowTotal × 98% (2% fee)
            const netPool = windowTotal * 98n / 100n

            for (let ci = 0; ci < nCells; ci++) {
                const idx = nWindows + wi * nCells + ci
                const r = data[idx]
                if (r?.status !== 'success') continue
                const cellStake = r.result as bigint | undefined
                if (!cellStake || cellStake === 0n) continue

                const slotId = getSlotKey(windowId, cellIds[ci])
                cellStakes[slotId] = Number(cellStake) / 1_000_000

                // multiplier = netPool / cellStake (scaled via integer math)
                const multiplier = Number(netPool * 1_000_000n / cellStake) / 1_000_000
                multipliers[slotId] = Math.min(multiplier, 999)
            }
        }

        const windowTotals: Record<number, number> = {}
        for (const windowId of bettableWindowIds) {
            windowTotals[windowId] = Number(rawWindowTotals[windowId] ?? 0n) / 1_000_000
        }

        return { multipliers, windowTotals, cellStakes }
    }, [data, bettableWindowIds, cellIds])
}
