name: Smart Contract Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version
        working-directory: contracts

      - name: Run Forge fmt
        run: |
          forge fmt --check
        working-directory: contracts
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        working-directory: contracts
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        working-directory: contracts
        id: test

      - name: Run Forge coverage
        run: |
          forge coverage --report summary --report lcov
        working-directory: contracts
        id: coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./contracts/lcov.info
          flags: foundry
          name: foundry-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Forge gas snapshot
        run: |
          forge snapshot
        working-directory: contracts
        id: snapshot
